/**
 * memory_provenance.mjs
 * 
 * TrustGraph-inspired Provenance Tracking for OpenClaw Memory
 * 
 * Every memory entry gets annotated with:
 * - source: where the knowledge came from
 * - confidence: how certain we are
 * - pathway: how it was derived (extracted/inferred/direct)
 * - history: change log
 * 
 * This turns "knowledge graph" into "context graph" — you can ask
 * not just "what do you know" but "how do you know that"
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, appendFileSync } from 'fs';
import { join, dirname } from 'path';
import { homedir } from 'os';

const PROVENANCE_DIR = join(homedir(), '.openclaw', 'memory', 'provenance');

/**
 * Provenance source types
 */
export const SourceType = {
  USER_INPUT: 'user_input',           // User explicitly said it
  USER_ACTION: 'user_action',         // Observed from user behavior
  FILE_READ: 'file_read',             // Extracted from a file
  TOOL_RESULT: 'tool_result',         // Output from a tool execution
  INFERRED: 'inferred',               // Deduced from other memories
  LLM_GENERATED: 'llm_generated',     // Generated by LLM reasoning
  EXTERNAL_API: 'external_api',        // From external service
  SESSION_REPLAY: 'session_replay',   // Learned from past session
  ONBOARDING: 'onboarding',            // Set up during initial setup
};

/**
 * Confidence levels
 */
export const ConfidenceLevel = {
  HIGH: 0.9,      // Direct observation / user confirmation
  MEDIUM: 0.7,    // Strong signal, some inference
  LOW: 0.4,       // Weak signal / heavy inference
  SPECULATIVE: 0.2, // Guess / single data point
};

/**
 * Pathway types — how knowledge was formed
 */
export const PathwayType = {
  DIRECT: 'direct',           // Stored as-is (user said it)
  EXTRACTED: 'extracted',     // Pulled from unstructured text
  PATTERN_MATCHED: 'pattern_matched', // Classified by pattern rules
  AGGREGATED: 'aggregated',   // Combined from multiple sources
  LLM_SYNTHESIZED: 'llm_synthesized', // Generated by LLM
  INFERRED: 'inferred',      // Logical deduction
};

/**
 * Create a provenance entry
 */
export function createProvenance({
  source = SourceType.USER_INPUT,
  confidence = ConfidenceLevel.MEDIUM,
  pathway = PathwayType.DIRECT,
  sourceFile = null,
  sourceSession = null,
  sourceTimestamp = null,
  derivedFrom = [],   // Array of provenance IDs this was derived from
  notes = '',
} = {}) {
  return {
    id: generateProvenanceId(),
    source,
    confidence,
    pathway,
    sourceFile,
    sourceSession,
    sourceTimestamp: sourceTimestamp || new Date().toISOString(),
    derivedFrom,  // References to other provenance IDs
    notes,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  };
}

/**
 * Generate a short unique ID
 */
function generateProvenanceId() {
  return 'prov_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 6);
}

/**
 * ProvenanceStore — persists provenance entries
 */
export class ProvenanceStore {
  constructor(options = {}) {
    this.dir = options.dir || PROVENANCE_DIR;
    this.entityIndex = join(this.dir, 'entity_index.jsonl');
    this.provenanceLog = join(this.dir, 'provenance.log');
  }

  init() {
    if (!existsSync(this.dir)) {
      mkdirSync(this.dir, { recursive: true });
    }
  }

  /**
   * Log a provenance event
   */
  log(entry) {
    this.init();
    const line = JSON.stringify({
      ...entry,
      _loggedAt: new Date().toISOString(),
    });
    appendFileSync(this.provenanceLog, line + '\n', 'utf8');
  }

  /**
   * Add provenance to an entity
   */
  addEntityProvenance(entityId, entityType, content, provenance) {
    this.init();

    const entry = {
      entityId,
      entityType,
      content: content.slice(0, 500), // Truncate for index
      contentHash: hashString(content),
      provenance: {
        ...provenance,
        id: provenance.id || generateProvenanceId(),
      },
    };

    this.log(entry);

    // Also update entity index for fast lookup
    const indexEntry = {
      entityId,
      entityType,
      pathway: provenance.pathway,
      source: provenance.source,
      confidence: provenance.confidence,
      createdAt: provenance.createdAt,
    };

    appendFileSync(this.entityIndex, JSON.stringify(indexEntry) + '\n', 'utf8');

    return entry.provenance.id;
  }

  /**
   * Get provenance chain for an entity (all ancestors)
   */
  getProvenanceChain(entityId, maxDepth = 10) {
    const chain = [];
    const visited = new Set();
    let currentId = entityId;
    let depth = 0;

    while (currentId && depth < maxDepth && !visited.has(currentId)) {
      visited.add(currentId);
      const entry = this.findInLog(currentId);
      if (!entry) break;
      chain.push(entry);
      currentId = entry.provenance?.derivedFrom?.[0];
      depth++;
    }

    return chain;
  }

  /**
   * Find a provenance entry in the log by entity ID
   */
  findInLog(entityId) {
    if (!existsSync(this.provenanceLog)) return null;

    const lines = readFileSync(this.provenanceLog, 'utf8').split('\n').filter(Boolean);
    // Read backwards for most recent
    for (let i = lines.length - 1; i >= 0; i--) {
      try {
        const entry = JSON.parse(lines[i]);
        if (entry.entityId === entityId) {
          return entry;
        }
      } catch { /* skip */ }
    }
    return null;
  }

  /**
   * Get entities by source type
   */
  getBySource(source, limit = 50) {
    if (!existsSync(this.entityIndex)) return [];

    const results = [];
    const lines = readFileSync(this.entityIndex, 'utf8').split('\n').filter(Boolean);

    for (const line of lines) {
      try {
        const entry = JSON.parse(line);
        if (entry.source === source) {
          results.push(entry);
          if (results.length >= limit) break;
        }
      } catch { /* skip */ }
    }

    return results;
  }

  /**
   * Get high-confidence memories
   */
  getHighConfidence(threshold = ConfidenceLevel.HIGH, limit = 50) {
    if (!existsSync(this.entityIndex)) return [];

    const results = [];
    const lines = readFileSync(this.entityIndex, 'utf8').split('\n').filter(Boolean);

    for (const line of lines) {
      try {
        const entry = JSON.parse(line);
        if (entry.confidence >= threshold) {
          results.push(entry);
          if (results.length >= limit) break;
        }
      } catch { /* skip */ }
    }

    return results;
  }

  /**
   * Format provenance as readable text
   */
  formatProvenanceChain(chain) {
    if (!chain || chain.length === 0) {
      return 'No provenance information available';
    }

    const lines = ['## Provenance Chain', ''];

    chain.forEach((entry, i) => {
      const indent = '  '.repeat(i);
      const prov = entry.provenance || {};
      const age = entry.createdAt ? getAgeString(entry.createdAt) : 'unknown age';

      lines.push(`${indent}${i + 1}. [${prov.pathway || 'unknown'}] ${prov.source || 'unknown source'}`);
      lines.push(`${indent}   confidence: ${(prov.confidence || 0).toFixed(1)} | ${age}`);

      if (prov.sourceFile) {
        lines.push(`${indent}   from: ${prov.sourceFile}`);
      }
      if (prov.notes) {
        lines.push(`${indent}   note: ${prov.notes}`);
      }
    });

    return lines.join('\n');
  }
}

/**
 * Simple string hash
 */
function hashString(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return Math.abs(hash).toString(16);
}

/**
 * Get human-readable age string
 */
function getAgeString(timestamp) {
  const diff = Date.now() - new Date(timestamp).getTime();
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(diff / 3600000);
  const days = Math.floor(diff / 86400000);

  if (days > 0) return `${days}d ago`;
  if (hours > 0) return `${hours}h ago`;
  if (minutes > 0) return `${minutes}m ago`;
  return 'just now';
}

/**
 * Singleton instance
 */
let _store = null;

export function getProvenanceStore() {
  if (!_store) {
    _store = new ProvenanceStore();
  }
  return _store;
}

/**
 * Convenience: annotate a memory entry with provenance
 */
export function annotateMemory(memoryEntry, options = {}) {
  const prov = createProvenance(options);
  return {
    ...memoryEntry,
    provenance: prov,
    provenanceId: prov.id,
  };
}

/**
 * Attach provenance to a Wing/Room/Hall memory
 * Integrates with the existing memory_system.py patterns
 */
export function attachToMemory(memoryContent, memoryType, options = {}) {
  const prov = createProvenance(options);

  return {
    content: memoryContent,
    memoryType, // 'decision' | 'preference' | 'milestone' | 'problem' | 'emotional'
    provenance: prov,
    hall: mapMemoryTypeToHall(memoryType),
  };
}

/**
 * Map memory types to Hall types (from Ebbinghaus system)
 */
function mapMemoryTypeToHall(memoryType) {
  const map = {
    decision: 'hall_facts',
    preference: 'hall_preferences',
    milestone: 'hall_events',
    problem: 'hall_discoveries',
    emotional: 'hall_advice',
  };
  return map[memoryType] || 'hall_events';
}

export default {
  SourceType,
  ConfidenceLevel,
  PathwayType,
  ProvenanceStore,
  createProvenance,
  getProvenanceStore,
  annotateMemory,
  attachToMemory,
};
