/**
 * spec-driven skill handler
 * Write structured specifications before writing any code.
 */

const args = process.argv.slice(2);
const command = args[0];

function showHelp() {
  return {
    handled: true,
    skill: 'spec-driven',
    response: `spec-driven — Spec-Driven Development

Usage:
  /spec [description]

Workflow (GATED — human review required between phases):
  Phase 1: SPECIFY — Write spec covering 6 areas
  Phase 2: PLAN — Generate technical implementation plan
  Phase 3: TASKS — Break plan into discrete tasks
  Phase 4: IMPLEMENT — Execute tasks one at a time

Six Core Areas:
  1. Objective — What & why, user stories, success criteria
  2. Commands — Full executable commands (build/test/lint/dev)
  3. Project Structure — Source/test/doc locations
  4. Code Style — Real code snippet example
  5. Testing Strategy — Framework, locations, coverage
  6. Boundaries — Always/Ask First/Never

Examples:
  /spec New user authentication system
  /spec REST API for task management
`,
  };
}

async function main() {
  if (!command || command === '--help' || command === '-h') {
    console.log(JSON.stringify(showHelp()));
    return;
  }

  // For now, return the workflow guide
  // Full spec writing would require interactive context
  const specTemplate = `# Spec: ${command || 'New Feature'}

## Objective
[What we're building and why. User stories or acceptance criteria.]

## Tech Stack
[Framework, language, key dependencies with versions]

## Commands
\`\`\`
Build: [command]
Test: [command]
Lint: [command]
Dev: [command]
\`\`\`

## Project Structure
\`\`\`
src/           → Application source code
tests/         → Unit and integration tests
docs/          → Documentation
\`\`\`

## Code Style
[One real code snippet showing your style]

## Testing Strategy
[Framework, test locations, coverage expectations]

## Boundaries
- **Always:** Run tests before commits, validate inputs
- **Ask first:** Database schema changes, adding dependencies
- **Never:** Commit secrets, remove failing tests

## Success Criteria
[Specific, testable conditions for "done"]

## Open Questions
[Anything unresolved that needs human input]

---

*Generated by spec-driven skill. Edit to customize.*
`;

  console.log(JSON.stringify({
    handled: true,
    skill: 'spec-driven',
    command,
    template: specTemplate,
    note: 'Edit the template above. Then proceed to PLAN phase with /plan.'
  }));
}

main();
